# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c9161d131f48f0bbd2c6069fff6df80291b51514300d6a0924b87bd3393fa855047096121f2c2446d6fc550a455a1d6db328cb2da911296895ce7360f223029

test:
  secret_key_base: a6f5a401cbf9e067b095360ef67dab8c2fb7b392fdf6a545efe9eb87e21c0311a6481f5ede816abee0eca34cf89467b44406b0c3f2b43f664eb676ed13fb8be6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
